development:
  adapter: mysql
  database: ublip_v2_development
  username: root
  password: 
  socket: /tmp/mysql.sock
  
gateway_xirgo_development:
  adapter: mysql
  database: xirgo_development
  username: root
  password:

gateway_xirgo-wired_development:
  adapter: mysql
  database: xirgo_wired_development
  username: root
  password:

test:
  adapter: mysql
  database: ublip_v2_test
  username: root
  password: a1ru135
  
gateway_xirgo_test:
  adapter: mysql
  database: xirgo_obd_test
  username: root
  password: a1ru135